[versions]
kotlin-version = "1.9.0"
agp-version = "7.3.0"
compose-version = "1.5.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp.version" }
android-library = { id = "com.android.library", version.ref = "agp.version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin.version" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.10.1" }
androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"
